<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="218" started-at="2021-05-03T16:06:02Z" finished-at="2021-05-03T16:06:02Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="218" started-at="2021-05-03T16:06:02Z" finished-at="2021-05-03T16:06:02Z">
      <class name="com.qa.tests.DemoTest">
        <test-method status="PASS" signature="add()[pri:0, instance:com.qa.tests.DemoTest@36f0f1be]" name="add" duration-ms="59" started-at="2021-05-03T21:36:02Z" finished-at="2021-05-03T21:36:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add -->
        <test-method status="FAIL" signature="div()[pri:0, instance:com.qa.tests.DemoTest@36f0f1be]" name="div" duration-ms="7" started-at="2021-05-03T21:36:02Z" finished-at="2021-05-03T21:36:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [10]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [10]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at org.testng.Assert.assertEquals(Assert.java:398)
	at com.qa.tests.DemoTest.div(DemoTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- div -->
        <test-method status="PASS" signature="mul()[pri:0, instance:com.qa.tests.DemoTest@36f0f1be]" name="mul" duration-ms="4" started-at="2021-05-03T21:36:02Z" finished-at="2021-05-03T21:36:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mul -->
        <test-method status="PASS" signature="sub()[pri:0, instance:com.qa.tests.DemoTest@36f0f1be]" name="sub" duration-ms="2" started-at="2021-05-03T21:36:02Z" finished-at="2021-05-03T21:36:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sub -->
      </class> <!-- com.qa.tests.DemoTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
